## Import Necessary Libraries / Dependencies

In [1]:
import pandas as pd

## Task 1: Determining what the most popular release year for 'Movies' on Netflix is.

In [2]:
netflix_df = pd.read_csv('/Users/emekaudemezue/Downloads/Data Analytics/Kaggle/Datasets/Raw/netflix_titles.csv')

In [3]:
netflix_df['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [4]:
netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
# The dataframe contains information on both Movies & TV Shows but for purposes of this 
# task we need just the Movies data so we will need to filter to get the data

In [5]:
movies_df = netflix_df[netflix_df['type']=='Movie']

In [6]:
movies_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

In [7]:
movies_df['count'] = 1
release_year_count = movies_df.groupby(['release_year']).sum().reset_index()[['release_year','count']]
release_year_count.sort_values(['count'], ascending=False)

/var/folders/12/hlwy0ls50bs_ptfnyp2g2k7m0000gp/T/ipykernel_2193/3361375040.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['count'] = 1

    release_year  count
69          2018    767
68          2017    767
67          2016    658
70          2019    633
71          2020    517
..           ...    ...
12          1961      1
14          1963      1
17          1966      1
5           1947      1
4           1946      1

[73 rows x 2 columns]

## Task 2: Determining year with most added content on the Netflix platform

In [ ]:
# Due to possible variations in the 'date_added' column and the fact that the column's 
#    property is 'object'. The column would need to be converted to the 'datetime' format and
#     then a new column created to hold just the year as we dont want to alter or change the 
#     information in the original 'date_added' column.

In [8]:
netflix_df['new_date'] = pd.to_datetime(netflix_df['date_added'])

netflix_df['date_added_year'] = netflix_df['new_date'].dt.year

netflix_df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_date,date_added_year
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021-09-25,2021.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021-09-24,2021.0

In [9]:
netflix_df['count'] = 1
date_added_count = netflix_df.groupby(['date_added_year']).sum().reset_index()[['date_added_year','count']]
date_added_count.sort_values(['count'], ascending=False)

    date_added_year  count
11           2019.0   2016
12           2020.0   1879
10           2018.0   1649
13           2021.0   1498
9            2017.0   1188
8            2016.0    429
7            2015.0     82
6            2014.0     24
3            2011.0     13
5            2013.0     11
4            2012.0      3
0            2008.0      2
1            2009.0      2
2            2010.0      1

##  Task 3: Aside 'Year', what is the most popular month to add new content?

In [10]:
netflix_df['date_added_month'] = netflix_df['new_date'].dt.month
netflix_df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_date,date_added_year,count,date_added_month
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021-09-25,2021.0,1,9.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021-09-24,2021.0,1,9.0

In [11]:
netflix_df['count'] = 1
month_added_count = netflix_df.groupby(['date_added_month']).sum().reset_index()[['date_added_month','count']]
month_added_count.sort_values(['count'], ascending=False)

    date_added_month  count
6                7.0    827
11              12.0    813
8                9.0    770
3                4.0    764
9               10.0    760
7                8.0    755
2                3.0    742
0                1.0    738
5                6.0    728
10              11.0    705
4                5.0    632
1                2.0    563

## Task 4: Movie with longest title in the dataset

In [12]:
movies_df = netflix_df[netflix_df['type']=='Movie']

In [13]:
movies_df['moviestitle_length'] = [len(title) for title in movies_df['title']]

/var/folders/12/hlwy0ls50bs_ptfnyp2g2k7m0000gp/T/ipykernel_2193/2305101630.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['moviestitle_length'] = [len(title) for title in movies_df['title']]

In [14]:
top_title_lengths = movies_df.sort_values(['moviestitle_length'], ascending=False)
top_title_lengths.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,new_date,date_added_year,count,date_added_month,moviestitle_length
5164,s5165,Movie,Jim & Andy: The Great Beyond - Featuring a Ver...,Chris Smith,Jim Carrey,"Canada, United States","November 17, 2017",2017,TV-MA,94 min,Documentaries,Through the lens of his stunningly immersive p...,2017-11-17,2017.0,1,11.0,104
8462,s8463,Movie,The Power of Grayskull: The Definitive History...,"Randall Lobb, Robert McCallum",NaN,"Canada, United States","August 24, 2018",2017,TV-14,96 min,Documentaries,This colorful documentary explores the origins...,2018-08-24,2018.0,1,8.0,88
3240,s3241,Movie,Mike Birbiglia: What I Should Have Said Was No...,NaN,Mike Birbiglia,United States,"November 22, 2019",2008,TV-MA,56 min,Stand-Up Comedy,Mike Birbiglia performs in this live concert s...,2019-11-22,2019.0,1,11.0,88
4851,s4852,Movie,Steve Martin and Martin Short: An Evening You ...,Marcus Raboy,"Steve Martin, Martin Short",United States,"May 25, 2018",2018,TV-14,74 min,Stand-Up Comedy,Longtime pals and showbiz icons Steve Martin a...,2018-05-25,2018.0,1,5.0,83
3479,s3480,Movie,Cultivating the Seas: History and Future of th...,Mana Yasuda,NaN,NaN,"September 28, 2019",2019,TV-PG,45 min,"Documentaries, International Movies",An in-depth look at the full-cycle breeding pr...,2019-09-28,2019.0,1,9.0,79

In [15]:
top_title_lengths.iloc[0]['title']

'Jim & Andy: The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton'

## Task 5: Actor/Actress with the most appearances in the Netflix Database

In [16]:
pd.options.display.max_colwidth = 400

# To display information that was hidden in column due to pandas column width restriction of '58'

In [17]:
title_and_cast_df = netflix_df[['title','cast']]
title_and_cast_df = title_and_cast_df.dropna() 
# titles with a 'NaN' result for 'cast' are dropped

In [28]:
cast_names_counter = {}

for index, row in title_and_cast_df.iterrows():
    movie_cast = row['cast']
    movie_cast_split = movie_cast.split(',')
    movie_cast_stripped = [name.strip().upper() for name in movie_cast_split] 
#   'Strip' method used to stripped extra white spaces for result to allow for truer count result
#     'Upper' method used to make results more uniform

    for name in movie_cast_stripped:
        cast_names_counter[name] = cast_names_counter.get(name, 0) + 1

dict(sorted(cast_names_counter.items(), key=lambda item: item[1], reverse = True))

{'ANUPAM KHER': 43,
 'SHAH RUKH KHAN': 35,
 'JULIE TEJWANI': 33,
 'NASEERUDDIN SHAH': 32,
 'TAKAHIRO SAKURAI': 32,
 'RUPA BHIMANI': 31,
 'AKSHAY KUMAR': 30,
 'OM PURI': 30,
 'YUKI KAJI': 29,
 'AMITABH BACHCHAN': 28,
 'PARESH RAWAL': 28,
 'BOMAN IRANI': 27,
 'RAJESH KAVA': 26,
 'VINCENT TONG': 26,
 'ANDREA LIBMAN': 25,
 'KAREENA KAPOOR': 25,
 'SAMUEL L. JACKSON': 24,
 'JOHN CLEESE': 24,
 'JIGNA BHARDWAJ': 23,
 'FRED TATASCIORE': 23,
 'TARA STRONG': 23,
 'DAISUKE ONO': 22,
 'JUNICHI SUWABE': 21,
 'AJAY DEVGN': 21,
 'ASHLEIGH BALL': 21,
 'KAY KAY MENON': 21,
 'NICOLAS CAGE': 21,
 'NAWAZUDDIN SIDDIQUI': 21,
 'ADAM SANDLER': 20,
 'DAVID ATTENBOROUGH': 20,
 'SALMAN KHAN': 20,
 'DAVID SPADE': 19,
 'YUICHI NAKAMURA': 19,
 'ERIN FITZGERALD': 19,
 'MAMORU MIYANO': 19,
 'MORGAN FREEMAN': 19,
 'JAMES FRANCO': 19,
 'SETH ROGEN': 19,
 'AI KAYANO': 19,
 'FRED ARMISEN': 19,
 'GULSHAN GROVER': 19,
 'VATSAL DUBEY': 18,
 'RAJESH SHARMA': 18,
 'FORTUNE FEIMSTER': 18,
 'DIANA KAARINA': 18,
 'YASHPAL SHARMA': 18,
 'KANA HANAZAWA': 18,
 'LAURA BAILEY': 18,
 'ANIL KAPOOR': 18,
 'DEBI DERRYBERRY': 18,
 'BRUCE WILLIS': 17,
 'MOLLY SHANNON': 17,
 'RAJPAL YADAV': 17,
 'BRIAN DRUMMOND': 17,
 'MICHELA LUCI': 17,
 'ALESSANDRO JULIANI': 17,
 'DANNY TREJO': 17,
 'PRIYANKA CHOPRA': 17,
 'ASRANI': 17,
 'JACKIE SHROFF': 17,
 'SAIF ALI KHAN': 17,
 'KATE HIGGINS': 17,
 'MAYA RUDOLPH': 16,
 'BLOSSOM CHUKWUJEKWU': 16,
 'MIYUKI SAWASHIRO': 16,
 'JUN FUKUYAMA': 16,
 'KARI WAHLGREN': 16,
 'TINNU ANAND': 16,
 'YOSHIMASA HOSOYA': 16,
 'HIROSHI KAMIYA': 16,
 'MIKE EPPS': 16,
 'LAURENCE FISHBURNE': 16,
 'SANJAY MISHRA': 16,
 'MANOJ JOSHI': 16,
 'ALFRED MOLINA': 16,
 'VIJAY RAAZ': 16,
 'KRISTEN STEWART': 16,
 'SAM VINCENT': 16,
 'MANOJ BAJPAYEE': 16,
 'TOMOKAZU SUGITA': 16,
 'AAMIR KHAN': 16,
 'HASSAN HOSNY': 16,
 'ROBB WELLS': 16,
 'MICHAEL PALIN': 16,
 'AMRISH PURI': 16,
 'CHRIS ROCK': 15,
 'GREY GRIFFIN': 15,
 'RICHARD MOFE-DAMIJO': 15,
 'SONAL KAUSHAL': 15,
 'PANKAJ TRIPATHI': 15,
 'WILLEM DAFOE': 15,
 'SANJAY DUTT': 15,
 'RADHIKA APTE': 15,
 'TAKEHITO KOYASU': 15,
 'KATHLEEN BARR': 15,
 'MICHAEL PEÑA': 15,
 'TOYIN ABRAHAM': 15,
 'KEITH DAVID': 15,
 'ERIN MATHEWS': 15,
 'BEN KINGSLEY': 15,
 'SEAN ASTIN': 15,
 'ANTONIO BANDERAS': 15,
 'ADIL HUSSAIN': 15,
 'JOHN PAUL TREMBLAY': 15,
 'ERIC IDLE': 15,
 'MOUSAM': 14,
 'SWAPNIL': 14,
 'BIMBO MANUEL': 14,
 'KAZUHIKO INOUE': 14,
 'YOSHITSUGU MATSUOKA': 14,
 'WOODY HARRELSON': 14,
 'SABINA MALIK': 14,
 'DEE BRADLEY BAKER': 14,
 'PIERCE BROSNAN': 14,
 'KENJIRO TSUDA': 14,
 'KULBHUSHAN KHARBANDA': 14,
 'TONY HALE': 14,
 'SHAKTI KAPOOR': 14,
 'RAJKUMMAR RAO': 14,
 'ROSARIO DAWSON': 14,
 'SHAFFY BELLO': 14,
 'YOKO HIKASA': 14,
 'RAMSEY NOUAH': 14,
 'DEMET AKBAĞ': 14,
 'KEVIN MICHAEL RICHARDSON': 14,
 'NATSUKI HANAE': 14,
 'TABITHA ST. GERMAIN': 14,
 'HELEN MIRREN': 14,
 'JOHNNY DEPP': 14,
 'LIAM NEESON': 14,
 'GUY PEARCE': 14,
 'JOHN TRAVOLTA': 14,
 'IAN JAMES CORLETT': 14,
 'JOHN ABRAHAM': 14,
 'IRRFAN KHAN': 14,
 'PAVAN MALHOTRA': 14,
 'SACHIN KHEDEKAR': 14,
 'KATRINA KAIF': 14,
 'SHARAT SAXENA': 14,
 'RANVIR SHOREY': 14,
 'SAMUEL WEST': 14,
 'TERRY JONES': 14,
 'JAMES MARSDEN': 13,
 'NASSAR': 13,
 'DENNIS QUAID': 13,
 'RYAN REYNOLDS': 13,
 'BRENDAN GLEESON': 13,
 'FUMIKO ORIKASA': 13,
 'SAORI HAYAMI': 13,
 'TINA MBA': 13,
 'STANLEY TUCCI': 13,
 'VIPIN SHARMA': 13,
 'DAVID KOECHNER': 13,
 'JOAN CUSACK': 13,
 'MITHUN CHAKRABORTY': 13,
 'RISHI KAPOOR': 13,
 'MOHNISH BAHL': 13,
 'MAHESH MANJREKAR': 13,
 'ABHISHEK BACHCHAN': 13,
 'AMY ADAMS': 13,
 'JOHN C. REILLY': 13,
 'MAAYA SAKAMOTO': 13,
 'ROB RIGGLE': 13,
 'OMONI OBOLI': 13,
 'CASSANDRA MORRIS': 13,
 'WILL FERRELL': 13,
 'LAURA LINNEY': 13,
 'JACKIE CHAN': 13,
 'DAVID CROSS': 13,
 'LIEV SCHREIBER': 13,
 'RAY LIOTTA': 13,
 'KEVIN HART': 13,
 'RICKY GERVAIS': 13,
 'NANA PATEKAR': 13,
 'RAJIT KAPOOR': 13,
 'RON PERLMAN': 13,
 'CORY DORAN': 13,
 'TIFFANY HADDISH': 13,
 'JULIE LEMIEUX': 13,
 'GERARD BUTLER': 13,
 'SEEMA BISWAS': 13,
 'JIM BROADBENT': 13,
 'SHAHID KAPOOR': 13,
 'JAMIE WATSON': 13,
 'ERIC PETERSON': 13,
 'AHMED HELMY': 13,
 'CINDY ROBINSON': 13,
 'GRAHAM CHAPMAN': 13,
 'TERRY GILLIAM': 13,
 'KEN JEONG': 12,
 'LORETTA DEVINE': 12,
 'SALMA HAYEK': 12,
 'HARRISON FORD': 12,
 'TOM KENNY': 12,
 'ROBERT PATRICK': 12,
 'HOUKO KUWASHIMA': 12,
 'JUNKO TAKEUCHI': 12,
 'RIKIYA KOYAMA': 12,
 'SATOSHI HINO': 12,
 'KATSUYUKI KONISHI': 12,
 'GLENN CLOSE': 12,
 'CHRISTINA HENDRICKS': 12,
 'AMERICA YOUNG': 12,
 'MARTIN LAWRENCE': 12,
 'KAZUYA NAKAI': 12,
 'WILLIAM H. MACY': 12,
 'ROBERT DE NIRO': 12,
 'JACK BLACK': 12,
 'EDDIE MURPHY': 12,
 'JOHN MALKOVICH': 12,
 'VIDYA BALAN': 12,
 'RIE KUGIMIYA': 12,
 'SAYAKA OHARA': 12,
 'ANTON YELCHIN': 12,
 'ANDY SAMBERG': 12,
 'DANNY MCBRIDE': 12,
 'JUSTIN LONG': 12,
 'JACKI WEAVER': 12,
 'HALLE BERRY': 12,
 'JOHN LEGUIZAMO': 12,
 'STEVEN YEUN': 12,
 'NAOMI WATTS': 12,
 'ROBERT PATTINSON': 12,
 'NOBUHIKO OKAMOTO': 12,
 'PAUL GIAMATTI': 12,
 'LONDON HUGHES': 12,
 'JUDY GREER': 12,
 'WILL SMITH': 12,
 'BRUCE GREENWOOD': 12,
 'GEORGE CLOONEY': 12,
 'BEN MENDELSOHN': 12,
 'RAGHUVIR YADAV': 12,
 'JOHN DUNSWORTH': 12,
 'STEVE BUSCEMI': 12,
 'ELYSE MALOWAY': 12,
 'BRITT MCKILLIP': 12,
 'SUSAN SARANDON': 12,
 'CHRIS PARNELL': 12,
 'DERMOT MULRONEY': 12,
 'JOHN MICHAEL HIGGINS': 12,
 'JOHNNY YONG BOSCH': 12,
 'SAURABH SHUKLA': 12,
 'MINAKO KOTOBUKI': 12,
 'KATHRYN HAHN': 12,
 'ADAM SCOTT': 12,
 'PATTON OSWALT': 12,
 'STEPHEN FRY': 12,
 'JEFF DUNHAM': 12,
 'PAUL DOBSON': 12,
 'JIMMY SHERGILL': 12,
 'CATE BLANCHETT': 12,
 'STEPHANIE SHEH': 12,
 'ANNA CLAIRE BARTLAM': 12,
 'NICK SWARDSON': 12,
 'JUHI CHAWLA': 12,
 'JASON SCHWARTZMAN': 12,
 'JAVED SHEIKH': 12,
 'JANE KRAKOWSKI': 11,
 'KEVIN JAMES': 11,
 'ROB SCHNEIDER': 11,
 'GARY OLDMAN': 11,
 'AMBER HEARD': 11,
 'DENZEL WASHINGTON': 11,
 'SAM SHEPARD': 11,
 'TOSHIYUKI MORIKAWA': 11,
 'MEGUMI HAN': 11,
 'KEITH WICKHAM': 11,
 'JOHNY LEVER': 11,
 'GARY COLE': 11,
 'SYLVESTER STALLONE': 11,
 'RYOHEI KIMURA': 11,
 'JAMES CROMWELL': 11,
 'MICHAEL MADSEN': 11,
 'BEN STILLER': 11,
 'CEDRIC THE ENTERTAINER': 11,
 'TUSSHAR KAPOOR': 11,
 'ARJUN RAMPAL': 11,
 'SUNIL SHETTY': 11,
 'DIVYA DUTTA': 11,
 'MANISHA KOIRALA': 11,
 'ELIZABETH BANKS': 11,
 'KAITO ISHIKAWA': 11,
 'HARVEY KEITEL': 11,
 'ALEC BALDWIN': 11,
 'TRACY MORGAN': 11,
 'JULIANNE MOORE': 11,
 'ANTHONY MACKIE': 11,
 'DAISUKE NAMIKAWA': 11,
 'KATHY BATES': 11,
 'JULIA ROBERTS': 11,
 'MARK HAMILL': 11,
 'TONY TODD': 11,
 'KOICHI YAMADERA': 11,
 'EMILE HIRSCH': 11,
 'FRANK GRILLO': 11,
 'PETER FACINELLI': 11,
 'CARLA GUGINO': 11,
 'WILL FORTE': 11,
 'NICOLE OLIVER': 11,
 'DON CHEADLE': 11,
 'LUCY LIU': 11,
 'JAY BARUCHEL': 11,
 'AOI YUKI': 11,
 'KENTA MIYAKE': 11,
 'STEPHEN LANG': 11,
 'ANTHONY ANDERSON': 11,
 'MICHAEL JAI WHITE': 11,
 'NICOLE ANTHONY': 11,
 'BOBBY CANNAVALE': 11,
 'JIGNA BHARADHWAJ': 11,
 'MATT DAMON': 11,
 'JESSICA CHASTAIN': 11,
 'KEANU REEVES': 11,
 'MARIO CASAS': 11,
 'MERYL STREEP': 11,
 'KONKONA SEN SHARMA': 11,
 'PAUL RUDD': 11,
 'CHRISTOPHER LEE': 11,
 'STEVE ZAHN': 11,
 'DANNY GLOVER': 11,
 'SEAN BEAN': 11,
 'STEVE COOGAN': 11,
 'VIOLA DAVIS': 11,
 'KATHRYN BERNARDO': 11,
 'RANI MUKERJI': 11,
 'MICHAEL SHANNON': 11,
 'KEEGAN-MICHAEL KEY': 11,
 'TERRY CREWS': 11,
 'SATISH SHAH': 11,
 'DALIP TAHIL': 11,
 'ABHAY DEOL': 11,
 'B.N. SHARMA': 11,
 'PATRICK WARBURTON': 11,
 'ALOK NATH': 11,
 'ALISON BRIE': 11,
 'MIKE SMITH': 11,
 'SATHYARAJ': 11,
 'TAY PING HUI': 11,
 "CHRIS O'DOWD": 10,
 'MARIA BELLO': 10,
 'YURI LOWENTHAL': 10,
 'VERA FARMIGA': 10,
 'KAPPEI YAMAGUCHI': 10,
 'CHIE NAKAMURA': 10,
 'KOHSUKE TORIUMI': 10,
 'YUKARI TAMURA': 10,
 'ROMI PARK': 10,
 'TERESA GALLAGHER': 10,
 'ADESUA ETOMI': 10,
 'JIDE KOSOKO': 10,
 'HIROKI YASUMOTO': 10,
 'WILL ARNETT': 10,
 'ALAN CUMMING': 10,
 'SEGUN ARINZE': 10,
 'DAVID HARBOUR': 10,
 'NICOLE KIDMAN': 10,
 'ANDY RICHTER': 10,
 'JANEANE GAROFALO': 10,
 'GREG KINNEAR': 10,
 'KURT RUSSELL': 10,
 'MIKE VOGEL': 10,
 'JADA PINKETT SMITH': 10,
 'NEHA DHUPIA': 10,
 'VIVEK OBEROI': 10,
 'EMRAAN HASHMI': 10,
 'MIKAKO KOMATSU': 10,
 'DAVID OYELOWO': 10,
 'BEVERLY NAYA': 10,
 'PRAKASH RAJ': 10,
 'SAM NEILL': 10,
 'ZOE SALDANA': 10,
 'MUKESH TIWARI': 10,
 'ANTHONY HOPKINS': 10,
 'NEIL PATRICK HARRIS': 10,
 'REINA UEDA': 10,
 'LUIS GUZMÁN': 10,
 'SHANNON CHAN-KENT': 10,
 'KEVIN CORRIGAN': 10,
 'IDRIS ELBA': 10,
 'JENNIFER GARNER': 10,
 'TOPHER GRACE': 10,
 'TAYLOR LAUTNER': 10,
 'LUIS TOSAR': 10,
 'MANOJ PAHWA': 10,
 'SUPRIYA PATHAK': 10,
 'JAMES REMAR': 10,
 'LENA HEADEY': 10,
 'BAYOUMI FOUAD': 10,
 'MOHAMMED THARWAT': 10,
 'NICK OFFERMAN': 10,
 'COLIN FARRELL': 10,
 'ANNA KENDRICK': 10,
 'JOHN GOODMAN': 10,
 'LAKE BELL': 10,
 'JOKE SILVA': 10,
 'KATE WALSH': 10,
 'CAMERON DIAZ': 10,
 'LUKE WILSON': 10,
 'LOUIS KOO': 10,
 'DUSTIN HOFFMAN': 10,
 'JON LOVITZ': 10,
 'T.J. MILLER': 10,
 'JANE LYNCH': 10,
 'CEZMI BASKIN': 10,
 'REBECCA SHOICHET': 10,
 'ALI NUHU': 10,
 'KIM COATES': 10,
 'KAZUYUKI OKITSU': 10,
 'SONALI KULKARNI': 10,
 'TERRENCE HOWARD': 10,
 'EWAN MCGREGOR': 10,
 'TIM BLAKE NELSON': 10,
 'ZACH GALIFIANAKIS': 10,
 'JASON ISAACS': 10,
 'BENEDICT CUMBERBATCH': 10,
 'MANAV KAUL': 10,
 'NATALIE DORMER': 10,
 'M・A・O': 10,
 'JONAH HILL': 10,
 'PATRICK WILSON': 10,
 'PAUL SCHRIER': 10,
 'NAT FAXON': 10,
 'RAHUL BOSE': 10,
 'AMY POEHLER': 10,
 'ALIA SHAWKAT': 10,
 'REZA RAHADIAN': 10,
 'JOHN CARROLL LYNCH': 10,
 'KALKI KOECHLIN': 10,
 'OPRAH WINFREY': 10,
 'EDDIE MARSAN': 10,
 'RUSSELL PETERS': 10,
 'ZAKIR HUSSAIN': 10,
 'RAJ BABBAR': 10,
 'NOLAN NORTH': 10,
 'AMRITA RAO': 10,
 'BRIJENDRA KALA': 10,
 'ARSHAD WARSI': 10,
 'SHREYAS TALPADE': 10,
 'HELENA BONHAM CARTER': 10,
 'KARAMJIT ANMOL': 10,
 'NOBUNAGA SHIMAZAKI': 10,
 'PREITY ZINTA': 10,
 'JEFF BENNETT': 10,
 'CAM CLARKE': 10,
 'DONNIE YEN': 10,
 'SONAM KAPOOR': 10,
 'PREM CHOPRA': 10,
 'SHRADDHA KAPOOR': 10,
 'HRITHIK ROSHAN': 10,
 'CHRISTOPHER MELONI': 10,
 'BRUCE DERN': 10,
 'GREY DELISLE': 10,
 'ATUL KULKARNI': 10,
 'RAMYA KRISHNAN': 10,
 'SARDAR SOHI': 10,
 'TAMANNAAH BHATIA': 10,
 'JOHNNY LEVER': 10,
 'GIANCARLO ESPOSITO': 9,
 'AISHWARYA RAI BACHCHAN': 9,
 'J.K. SIMMONS': 9,
 'KUNAL KAPOOR': 9,
 'BEN DISKIN': 9,
 'SATSUKI YUKINO': 9,
 'AKIO OTSUKA': 9,
 'KIKUKO INOUE': 9,
 'TETSUYA KAKIHARA': 9,
 'YUHKO KAIDA': 9,
 'JACK WHITEHALL': 9,
 'SOLA SOBOWALE': 9,
 'KOJI YUSA': 9,
 'MARY ELIZABETH WINSTEAD': 9,
 'ALEXX EKUBO': 9,
 'SARAH NATOCHENNY': 9,
 'CHERAMI LEIGH': 9,
 'GABRIEL IGLESIAS': 9,
 'ROB RACKSTRAW': 9,
 'JENNIFER JASON LEIGH': 9,
 'WANDA SYKES': 9,
 'JENNIFER COOLIDGE': 9,
 'TERENCE STAMP': 9,
 'JAMES HONG': 9,
 'AMANDA SEYFRIED': 9,
 'RICHARD JENKINS': 9,
 'JAY O. SANDERS': 9,
 'SHAWN YUE': 9,
 'MARTIN SHORT': 9,
 'JOEL MCHALE': 9,
 'DIEDRICH BADER': 9,
 'RAJENDRANATH ZUTSHI': 9,
 'KANGANA RANAUT': 9,
 'RANDEEP HOODA': 9,
 'SANDRA OH': 9,
 'GILLIAN JACOBS': 9,
 'BILL BURR': 9,
 'ERICA LINDBECK': 9,
 'ASHLEY GREENE': 9,
 'SCOTT ADKINS': 9,
 'LEONARDO DICAPRIO': 9,
 'BILL HADER': 9,
 'THOMAS JANE': 9,
 'JESSICA ALBA': 9,
 'JOSEPH GORDON-LEVITT': 9,
 'CRAIG ROBINSON': 9,
 'BRUCE MCGILL': 9,
 'GEORGE LOPEZ': 9,
 'KEITH SILVERSTEIN': 9,
 'WALTON GOGGINS': 9,
 'KELSEY GRAMMER': 9,
 'DAKOTA FANNING': 9,
 'MICHAEL SHEEN': 9,
 'CAM GIGANDET': 9,
 'MICHELLE YEOH': 9,
 'IRETI DOYLE': 9,
 'BILL MURRAY': 9,
 'DEEPAK DOBRIYAL': 9,
 'CATHY WESELUCK': 9,
 'MAUDY KOESNAEDI': 9,
 'MAKRAND DESHPANDE': 9,
 'MIKE MYERS': 9,
 'SETH GREEN': 9,
 'SAM ROCKWELL': 9,
 'LAM SUET': 9,
 'JOE PANTOLIANO': 9,
 'LACEY CHABERT': 9,
 'CLANCY BROWN': 9,
 'JUDI DENCH': 9,
 'CHRIS PINE': 9,
 'ZACHARY QUINTO': 9,
 'MARC MARON': 9,
 'SACHA BARON COHEN': 9,
 'MICHAEL DOUGLAS': 9,
 'COLM FEORE': 9,
 'PAUL BETTANY': 9,
 'VIVICA A. FOX': 9,
 'SCOOT MCNAIRY': 9,
 'ILIZA SHLESINGER': 9,
 "CATHERINE O'HARA": 9,
 'ALFRE WOODARD': 9,
 'KAZUHIRO YAMAJI': 9,
 'STEVE BLUM': 9,
 'ROSAMUND PIKE': 9,
 'FOREST WHITAKER': 9,
 'HUGH BONNEVILLE': 9,
 'ADAM PALLY': 9,
 'MIKE COLTER': 9,
 'BASSEM SAMRA': 9,
 'SAM WORTHINGTON': 9,
 'CARLOS ALAZRAQUI': 9,
 'SALIH KALYON': 9,
 'JENNIFER EHLE': 9,
 'PARKER POSEY': 9,
 'GUGU MBATHA-RAW': 9,
 'TONI COLLETTE': 9,
 'MICHAEL STUHLBARG': 9,
 'VIR DAS': 9,
 'MAHERSHALA ALI': 9,
 'PATRICIA CLARKSON': 9,
 'ROB CORDDRY': 9,
 'JAVED JAFFREY': 9,
 'OSCAR ISAAC': 9,
 'SHEEBA CHADDHA': 9,
 'JOHN DIMAGGIO': 9,
 'JIM CUMMINGS': 9,
 'MANISH CHAUDHARY': 9,
 'KEVIN COSTNER': 9,
 'FRANK LANGELLA': 9,
 'RASHIDA JONES': 9,
 'MAE WHITMAN': 9,
 'DANIEL PADILLA': 9,
 'UMA THURMAN': 9,
 'KIERNAN SHIPKA': 9,
 'JOROSS GAMBOA': 9,
 'JAKE GYLLENHAAL': 9,
 'COMMON': 9,
 'JENNY SLATE': 9,
 'FRANK WELKER': 9,
 'ANDREW BACHELOR': 9,
 'AUBREY PLAZA': 9,
 'GOVIND NAMDEO': 9,
 'FARIDA JALAL': 9,
 'HARUKA TOMATSU': 9,
 'MANU RISHI CHADHA': 9,
 'KRISTEN BELL': 9,
 'GURPREET GUGGI': 9,
 'ERI KITAMURA': 9,
 'NICOLAS AQUI': 9,
 'LOTFY LABIB': 9,
 'JIM GAFFIGAN': 9,
 'STEPHEN TOBOLOWSKY': 9,
 'PEDRO CASABLANC': 9,
 'DANNY DENZONGPA': 9,
 'MURLI SHARMA': 9,
 'MARIA BAMFORD': 9,
 'SHINICHIRO MIKI': 9,
 'KARISMA KAPOOR': 9,
 'VIKRAM GOKHALE': 9,
 'REEMA LAGOO': 9,
 'CHLOË GRACE MORETZ': 9,
 'SALLI SAFFIOTI': 9,
 'CARMEN MACHI': 9,
 'CHRISTOPHER PLUMMER': 9,
 'VANESSA HUDGENS': 8,
 'SAHAJAK BOONTHANAKIT': 8,
 'BOB ODENKIRK': 8,
 'DAVID KAYE': 8,
 'ROGER CRAIG SMITH': 8,
 'SNOOP DOGG': 8,
 'KOJI TSUJITANI': 8,
 'KUMIKO WATANABE': 8,
 'MAMIKO NOTO': 8,
 'TOMOKAZU SEKI': 8,
 'HIROYUKI YOSHINO': 8,
 'HIRO SHIMONO': 8,
 'VIJAY SETHUPATHI': 8,
 'MICHIEL HUISMAN': 8,
 'AYO MAKUN': 8,
 'EMMA ROBERTS': 8,
 'LUDACRIS': 8,
 'NATASHA LYONNE': 8,
 'MICHELLE BUTEAU': 8,
 'MADHURI DIXIT': 8,
 'HIMANI SHIVPURI': 8,
 'BEN WHISHAW': 8,
 'JOSH LUCAS': 8,
 'KELLAN LUTZ': 8,
 'MARK STRONG': 8,
 'KENSHO ONO': 8,
 'TATSUHISA SUZUKI': 8,
 'GAEL GARCÍA BERNAL': 8,
 'SARAH JESSICA PARKER': 8,
 'CHADWICK BOSEMAN': 8,
 'CRISPIN GLOVER': 8,
 'DYLAN MCDERMOTT': 8,
 'KRISTIN SCOTT THOMAS': 8,
 'JON BERNTHAL': 8,
 'URMILA MATONDKAR': 8,
 'NSE IKPE-ETIM': 8,
 'RITEISH DESHMUKH': 8,
 'SATISH KAUSHIK': 8,
 'IMRAN KHAN': 8,
 'ARBAAZ KHAN': 8,
 'SAMY MAGHAWRY': 8,
 'BOB BALABAN': 8,
 'NASSER': 8,
 'MAAYA UCHIDA': 8,
 'FEMI ADEBAYO': 8,
 'MARTIN SHEEN': 8,
 'STELLAN SKARSGÅRD': 8,
 'YUI HORIE': 8,
 'YOGI BABU': 8,
 'FALZ': 8,
 'DEEPIKA PADUKONE': 8,
 'LEONARDO SBARAGLIA': 8,
 'OLIVER PLATT': 8,
 'TOM HANKS': 8,
 'JESSE PLEMONS': 8,
 'KEIJI FUJIWARA': 8,
 'PHILIP BAKER HALL': 8,
 'SEANN WILLIAM SCOTT': 8,
 'JEFF BRIDGES': 8,
 'TOMMY LEE JONES': 8,
 'BRADLEY COOPER': 8,
 'CHRIS ATTOH': 8,
 'RANA DAGGUBATI': 8,
 'STEPHEN ROOT': 8,
 'ELLE FANNING': 8,
 'JACKSON RATHBONE': 8,
 'SHIA LABEOUF': 8,
 'SARAH GADON': 8,
 'JESSE EISENBERG': 8,
 'REESE WITHERSPOON': 8,
 'BRYCE PAPENBROOK': 8,
 'OCTAVIA SPENCER': 8,
 'ALISON PILL': 8,
 'MINDY STERLING': 8,
 'HEATHER GRAHAM': 8,
 'MARK WAHLBERG': 8,
 'JOSH DUHAMEL': 8,
 'ROONEY MARA': 8,
 'JENNIFER ANISTON': 8,
 'JAKE JOHNSON': 8,
 'AMI KOSHIMIZU': 8,
 'SHIZUKA ITO': 8,
 'SIMON PEGG': 8,
 'TOBY HUSS': 8,
 'LESLIE BIBB': 8,
 'KEVIN SPACEY': 8,
 'KATE WINSLET': 8,
 'BEN AFFLECK': 8,
 'CIARÁN HINDS': 8,
 'BRAD PITT': 8,
 'RYOTARO OKIAYU': 8,
 'PAUL REISER': 8,
 'JAMES COSMO': 8,
 'SOMA SAITO': 8,
 'DEMIÁN BICHIR': 8,
 'MISSI PYLE': 8,
 'LISA KUDROW': 8,
 'VINNIE JONES': 8,
 'JASON BATEMAN': 8,
 'TITUSS BURGESS': 8,
 'AARON PAUL': 8,
 'ATSUKO TANAKA': 8,
 'SMITA JAYKAR': 8,
 'ROBERT FORSTER': 8,
 'NEENA GUPTA': 8,
 'KUMUD MISHRA': 8,
 'ADITI RAO HYDARI': 8,
 'RIO DEWANTO': 8,
 'ENYINNA NWIGWE': 8,
 'T.I.': 8,
 'JEFFREY WRIGHT': 8,
 'DAVID SCHWIMMER': 8,
 'SAURAV CHAKRABORTY': 8,
 'SELMA BLAIR': 8,
 'OLIVIA COLMAN': 8,
 'VINAY PATHAK': 8,
 'CENGIZ BOZKURT': 8,
 'WALE OJO': 8,
 'YILMAZ ERDOĞAN': 8,
 'RATNA PATHAK SHAH': 8,
 'BEA ALONZO': 8,
 'MANAV VIJ': 8,
 'MELISSA LEO': 8,
 'JOHN CUSACK': 8,
 'MADHAVAN': 8,
 'FARHAN AKHTAR': 8,
 'ALYSON LEIGH ROSENFELD': 8,
 'HIROAKI HIRATA': 8,
 'MACON BLAIR': 8,
 'DEON COLE': 8,
 'KAT GRAHAM': 8,
 'BIPASHA BASU': 8,
 'HALUK BILGINER': 8,
 "VINCENT D'ONOFRIO": 8,
 'BEN SCHWARTZ': 8,
 'JOHN MULANEY': 8,
 'JON FAVREAU': 8,
 'AMY SEDARIS': 8,
 'JAMES FOX': 8,
 'KISHORE KADAM': 8,
 'LILLETE DUBEY': 8,
 'KRISTEN SCHAAL': 8,
 'SARAH PAULSON': 8,
 'BRITTANY SNOW': 8,
 'ED HELMS': 8,
 'IKO UWAIS': 8,
 'SHABANA AZMI': 8,
 'JON HAMM': 8,
 'HUGO WEAVING': 8,
 'MICHAEL GROSS': 8,
 'CHRISTOPHER MINTZ-PLASSE': 8,
 'JEFF GARLIN': 8,
 'SHARON STONE': 8,
 'RILEY KEOUGH': 8,
 'SUBODH BHAVE': 8,
 'KEN MARINO': 8,
 'BOBBY DEOL': 8,
 'ALLISON JANNEY': 8,
 'JOHN RHYS-DAVIES': 8,
 'KAREN STRASSMAN': 8,
 'AUDU PADEN': 8,
 'EVAN SMITH': 8,
 'TABU': 8,
 'DIMPLE KAPADIA': 8,
 'JASON FLEMYNG': 8,
 'NICHOLAS HOULT': 8,
 'EZZAT ABOU AOUF': 8,
 'KIRON KHER': 8,
 'PRAN': 8,
 'ZEENAT AMAN': 8,
 'LARA DUTTA': 8,
 'MICHAEL CERA': 8,
 'EMORY COHEN': 8,
 'ARYA BABBAR': 8,
 'PURAB KOHLI': 8,
 'PRABHAS': 8,
 'AL PACINO': 8,
 'NIRMAL RISHI': 8,
 'AKI TOYOSAKI': 8,
 'MICHAEL DOBSON': 8,
 'EMMA STONE': 8,
 'TANNISHTHA CHATTERJEE': 8,
 'CARRIE-ANNE MOSS': 8,
 'RASIKA DUGAL': 8,
 'THOMAS MANN': 8,
 'DAVID STRATHAIRN': 8,
 'SANTOSH JUVEKAR': 8,
 'ANUSHKA SHETTY': 8,
 'ARJUN MATHUR': 8,
 'MATT HILL': 8,
 'KADER KHAN': 8,
 'JEANETTE AW': 8,
 'REKHA': 8,
 'MELANIE LYNSKEY': 8,
 'SMITA MALHOTRA': 8,
 'HENRY THOMAS': 7,
 'ANNABETH GISH': 7,
 'LOGAN MARSHALL-GREEN': 7,
 'BLANCA SUÁREZ': 7,
 'COLIN QUINN': 7,
 'TREVOR DEVALL': 7,
 'INI DIMA-OKOJIE': 7,
 'KEMI LALA AKINDOJU': 7,
 'TONI TONES': 7,
 'ETHAN HAWKE': 7,
 'CLIFF CURTIS': 7,
 'EVA MENDES': 7,
 'DAKORE AKANDE': 7,
 'NORIKO HIDAKA': 7,
 'NICOLE BYER': 7,
 'NORIAKI SUGIYAMA': 7,
 'SHOWTARO MORIKUBO': 7,
 'NANA MIZUKI': 7,
 'HIROTAKA SUZUOKI': 7,
 'SHARON OOJA': 7,
 'KENJI NOJIMA': 7,
 'PATRICK STEWART': 7,
 'FUNKE AKINDELE': 7,
 'UM SANG-HYUN': 7,
 'GIOVANNI RIBISI': 7,
 'MICHAEL KEATON': 7,
 'AKSHAY OBEROI': 7,
 'MARK RUFFALO': 7,
 'KEVIN BACON': 7,
 'LIN SHAYE': 7,
 'SIGOURNEY WEAVER': 7,
 'BENJAMIN BRATT': 7,
 'JUDE LAW': 7,
 'NATALIE PORTMAN': 7,
 'DONALD SUTHERLAND': 7,
 'CHANNING TATUM': 7,
 'SCOTT PORTER': 7,
 'JOHN TURTURRO': 7,
 'ANGELA BASSETT': 7,
 'BERNIE MAC': 7,
 'YUKI ONO': 7,
 'KIANA MADEIRA': 7,
 'KAL PENN': 7,
 'STERLING K. BROWN': 7,
 'ASHTON KUTCHER': 7,
 'JEFFREY TAMBOR': 7,
 'PAUL REUBENS': 7,
 'EDDIE IZZARD': 7,
 'BURT YOUNG': 7,
 'SARAH SILVERMAN': 7,
 'RANDALL PARK': 7,
 'DAVE CHAPPELLE': 7,
 'LOUIS C.K.': 7,
 'TANTOO CARDINAL': 7,
 'DARSHAN JARIWALA': 7,
 'AVTAR GILL': 7,
 'SONALI BENDRE': 7,
 'SUNNY LEONE': 7,
 'ANDY SERKIS': 7,
 'TOM WILKINSON': 7,
 'OLGA KURYLENKO': 7,
 'BILL SMITROVICH': 7,
 'JAY DUPLASS': 7,
 'DAVID TENNANT': 7,
 'ALICIA VIKANDER': 7,
 'CATHERINE KEENER': 7,
 'JORGE DIAZ': 7,
 'MAXI IGLESIAS': 7,
 'JOEL COURTNEY': 7,
 'MOLLY RINGWALD': 7,
 'WATARU TAKAGI': 7,
 'IMANOL ARIAS': 7,
 'ERNESTO ALTERIO': 7,
 'JAMES WEN': 7,
 'ANGELINA JOLIE': 7,
 'CHRISTOPHER WALKEN': 7,
 'ANNA FARIS': 7,
 'JAMES CAAN': 7,
 'CHARLIE SHEEN': 7,
 'MICHAEL IRONSIDE': 7,
 'LEE TOCKAR': 7,
 'DIANE KEATON': 7,
 'MARCIA GAY HARDEN': 7,
 'MAURICE LAMARCHE': 7,
 'RYAN PHILLIPPE': 7,
 'CHRIS EVANS': 7,
 'CHRISTIAN BALE': 7,
 'JAMIE FOXX': 7,
 'JOSÉ CORONADO': 7,
 'EMILIO GUTIÉRREZ CABA': 7,
 'MARTIN FREEMAN': 7,
 'DIEGO LUNA': 7,
 'LOCHLYN MUNRO': 7,
 'BENJAMIN FLORES JR.': 7,
 'JAMES ARNOLD TAYLOR': 7,
 'MARYKE HENDRIKSE': 7,
 'BOBBY MOYNIHAN': 7,
 'BILLY BURKE': 7,
 'ELIZABETH REASER': 7,
 'BRYCE DALLAS HOWARD': 7,
 'KENYU HORIUCHI': 7,
 'BILL PULLMAN': 7,
 'KEHINDE BANKOLE': 7,
 'BELLA THORNE': 7,
 'HUGO SILVA': 7,
 'FRED WILLARD': 7,
 'KATE BERLANT': 7,
 'SMITA TAMBE': 7,
 'SHAMMI KAPOOR': 7,
 'VIKRANT MASSEY': 7,
 'JAMIE BELL': 7,
 'ROB LOWE': 7,
 'JOE DON BAKER': 7,
 'CHIWETEL EJIOFOR': 7,
 'JASON SUDEIKIS': 7,
 'CLIVE OWEN': 7,
 'STEPHEN CAMPBELL MOORE': 7,
 'HISAKO KANEMOTO': 7,
 'TARAJI P. HENSON': 7,
 'CUBA GOODING JR.': 7,
 'MERRITT WEVER': 7,
 'JASON MANTZOUKAS': 7,
 'SORA AMAMIYA': 7,
 'CHANDAN ROY SANYAL': 7,
 'DIBYENDU BHATTACHARYA': 7,
 'SARAH SHAHI': 7,
 'AISLINN DERBEZ': 7,
 'JAMES PUREFOY': 7,
 'MICHAEL KENNETH WILLIAMS': 7,
 'SHUICHI IKEDA': 7,
 'WHOOPI GOLDBERG': 7,
 'JOJU GEORGE': 7,
 'SHEA WHIGHAM': 7,
 'ADRIAN PETRIW': 7,
 'MARLON WAYANS': 7,
 'RYOTA OSAKA': 7,
 'MOLLY PARKER': 7,
 'TOM SIZEMORE': 7,